version: '3.9'
services:
  api:
    container_name: auth-api
    image: auth-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    